### ISSUE TITLE
Write a version of this demo in Python using the redis-py client.

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/keyspace-notifications-node-redis#1]
Write a version of this demo in Python using the redis-py client.  You'll need to move the existing node.js project into a new folder called `nodejs`, then create a `python` folder and add a new script called `main.py` in there.  This should perform the same functionality as the existing Node `index.js` script does, so study that carefully.

In your `python` folder you'll also want to include a `README.md` describing how to set up and run your code.  Be sure to use a Python virtual environment when you do that (use Python 3's built in `venv` module) and provide a `requirements.txt` for Pip containing your dependencies.

Move the Node.js specific setup instructions into a new `README.md` file in the new `nodejs` folder.  Edit the repo's main `README.md` to remove the node specific setup, retaining the overall project overview and instructions on how to start Redis etc.

Finally, don't worry about this repo being called `keyspace-notifications-node-redis` we'll rename it to something more appropriate when there's more than 1 language implementation on the main branch.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by lucacillario** [comment]
@simonprickett @SuzeShardlow can i work on this?

**Comment by SuzeShardlow** [comment]
Yes @lucacillario, I've assigned this to you, looking forward to seeing your PR in the next couple of days. Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/
